# config.yaml

# Path to the Spark SQL warehouse directory (used for managed tables)
warehouse_dir: ./data/spark-warehouse

# Root path for external tables (used for external Delta tables)
external_path: ./data/external-table

# Optional: Logging level or logger config
log_level: INFO
